version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./.docker/mongodb/data:/data/db
    ports:
      - '27017-27019:27017-27019'

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=erp
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: nc -z localhost 5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
        - 5672:5672
        - 15672:15672

  service-registry:
    build:
      context: ./service-registry
      args:
        SERVICE_PORT: 50250
    restart: always
    volumes:
      - ./service-registry:/usr/src/app
    ports:
      - 50250:50250

  auth-service:
    build:
      context: ./auth-service
      args:
        SERVICE_PORT: 50270
    depends_on:
      - service-registry
      - mongodb
    restart: always
    environment:
      REGISTRY_URL: http://service-registry:50250
    volumes:
      - ./auth-service:/usr/src/app
    ports:
      - 50270:50270

  file-service:
    build:
      context: ./file-service
      args:
        SERVICE_PORT: 50290
    depends_on:
      - service-registry
    restart: always
    environment:
      REGISTRY_URL: http://service-registry:50250
    volumes:
      - ./file-service:/usr/src/app
      - ./.docker/file-service/data/:/usr/src/app/files
    ports:
      - 50290:50290

  item-service:
    build:
      context: ./item-service
      args:
        SERVICE_PORT: 50280
    depends_on:
      - service-registry
      - postgres
    restart: always
    environment:
      REGISTRY_URL: http://service-registry:50250
    volumes:
      - ./item-service:/usr/src/app
    ports:
      - 50280:50280

  main-service:
    build:
      context: ./main-app
      args:
        SERVICE_PORT: 5000
    depends_on:
      - service-registry
    restart: always
    environment:
      REGISTRY_URL: http://service-registry:50250
    volumes:
      - ./main-app:/usr/src/app
    ports:
      - 5000:5000
  ui-app:
    build:
      context: ./ui-app
      args:
        SERVICE_PORT: 8080
    depends_on:
      - main-service
    restart: always
    environment:
      MAIN_APP_URL: http://localhost:5000
    volumes:
      - ./ui-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080

volumes:
  postgres-volume:
    driver: local

