# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auth Service

on:
  push:
    paths:
      - 'auth-service/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        working-directory: ./auth-service
        env:
          CI: true
        run: npm install
      - name: Lint JS
        working-directory: ./auth-service
        env:
          CI: true
        run: npm run lint

